Add context to errors
exaring/release-cli pull request #9
Opened 2019-10-09 15:19 UTC by hikhvar

Use the error wrapping introduced by go 1.13

2020-02-19 08:40 UTC, costela requested changes

2020-02-19 08:40 UTC, costela commented on cmd/release/main.go
> +
```suggestion
```

2020-02-20 07:21 UTC, hikhvar commented on cmd/release/main.go
> +
Fixed

2020-02-20 07:22 UTC, hikhvar commented
Fixed the whitespace. PTAL.

2020-02-20 09:02 UTC, costela approved these changes

2020-02-20 09:04 UTC, merged